# Generated by Django 4.1.7 on 2023-05-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=20, null=True)),
                ('category_img', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
