# Generated by Django 4.1.7 on 2023-05-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redditApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=30, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, max_length=20, null=True)),
                ('Brand', models.CharField(blank=True, max_length=20, null=True)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
