# Generated by Django 4.1.7 on 2023-05-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signupdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=40, null=True)),
                ('Phone_number', models.IntegerField(blank=True, null=True)),
                ('Password', models.CharField(blank=True, max_length=60, null=True)),
                ('User_Image', models.ImageField(blank=True, null=True, upload_to='user_dp')),
            ],
        ),
    ]
