# Generated by Django 4.1.7 on 2023-05-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
