# Generated by Django 4.1.7 on 2023-06-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_contactdb_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(max_length=59, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Pro_Image', models.ImageField(blank=True, null=True, upload_to='cartimg')),
            ],
        ),
    ]
