# Generated by Django 4.1.7 on 2023-06-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Pro_Image',
        ),
    ]
