# Generated by Django 4.1.7 on 2023-06-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_cartdb_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Description',
            field=models.CharField(blank=True, max_length=59, null=True),
        ),
    ]
